import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { VerifyHeader } from '@/components/layout/global/header/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const geist_font = Geist({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`antialiased ${geist_font.className}`}>
        <Toaster position="top-center" duration={2000} />
        <VerifyHeader />
        {children}
      </body>
    </html>
  );
}
